const Portafoglio = require('../models/Portafoglio');
const RealPortfolioOperation = require('../models/RealPortfolioOperation');
const RealPortfolioEtf = require('../models/RealPortfolioEtf');
const RealPortfolioOrder = require('../models/RealPortfolioOrder');
const ETF = require('../models/ETF');
const EtfQuotation = require('../models/EtfQuotation');
const { sequelize } = require('../config/database');
const { QueryTypes, Op } = require('sequelize');

const toApi = (portfolio) => {
  const p = portfolio.toJSON ? portfolio.toJSON() : portfolio;
  return {
    id: p.id,
    name: p.nome,
    description: p.descrizione,
    status: p.status,
    tipo: p.tipo,
    createdAt: p.dataCreazione,
    updatedAt: p.dataModifica,
  };
};

exports.getRealPortfolios = async (req, res, next) => {
  try {
    const portfolios = await Portafoglio.findAll({
      where: { status: 'open', tipo: 'reale', userId: req.user.id },
      include: [{ model: RealPortfolioOrder, as: 'realOrder', required: false, attributes: ['position'] }],
      order: [['dataCreazione', 'ASC']]
    });
    portfolios.sort((a,b) => {
      const ap=a.realOrder?.position, bp=b.realOrder?.position;
      if(ap != null && bp != null) return ap-bp;
      if(ap != null) return -1;
      if(bp != null) return 1;
      return new Date(a.dataCreazione).getTime()-new Date(b.dataCreazione).getTime();
    });
    res.status(200).json({ success: true, data: portfolios.map(toApi) });
  } catch (error) { next(error); }
};

exports.createRealPortfolio = async (req, res, next) => {
  const transaction = await sequelize.transaction();
  try {
    const name = String(req.body?.name ?? '').trim();
    if (!name) {
      await transaction.rollback();
      return res.status(400).json({ success: false, error: 'Nome portafoglio obbligatorio' });
    }
    const description = String(req.body?.description ?? '').trim() || null;
    const existing = await Portafoglio.findAll({ where: { userId: req.user.id }, attributes: ['nome'], transaction });
    if (existing.some((item) => String(item.nome).trim().toLocaleLowerCase() === name.toLocaleLowerCase())) {
      await transaction.rollback();
      return res.status(409).json({ success: false, error: 'Nome portafoglio già utilizzato' });
    }

    // Lock only the base portfolio rows. PostgreSQL cannot apply FOR UPDATE
    // to the nullable side of the LEFT OUTER JOIN generated by the optional
    // realOrder include; that SQL error aborts the whole transaction.
    const realPortfolios = await Portafoglio.findAll({
      where: { userId: req.user.id, tipo: 'reale', status: 'open' },
      order: [['dataCreazione', 'ASC']],
      transaction,
      lock: transaction.LOCK.UPDATE
    });
    const persistedOrder = await RealPortfolioOrder.findAll({
      where: { userId: req.user.id },
      attributes: ['realPortfolioId', 'position'],
      transaction
    });
    const orderByPortfolioId = new Map(
      persistedOrder.map((row) => [String(row.realPortfolioId), Number(row.position)])
    );
    if (realPortfolios.length >= 5) {
      await transaction.rollback();
      return res.status(409).json({ success: false, error: 'Puoi avere al massimo 5 portafogli reali' });
    }

    realPortfolios.sort((a,b) => {
      const ap=orderByPortfolioId.get(String(a.id)), bp=orderByPortfolioId.get(String(b.id));
      if(ap != null && bp != null) return ap-bp;
      if(ap != null) return -1;
      if(bp != null) return 1;
      return new Date(a.dataCreazione).getTime()-new Date(b.dataCreazione).getTime();
    });

    const portfolio = await Portafoglio.create({
      nome: name,
      descrizione: description,
      tipo: 'reale',
      status: 'open',
      userId: req.user.id
    }, { transaction });

    const completeOrder = [...realPortfolios.map(p => String(p.id)), String(portfolio.id)];
    await RealPortfolioOrder.destroy({ where: { userId: req.user.id }, transaction });
    await RealPortfolioOrder.bulkCreate(
      completeOrder.map((realPortfolioId, position) => ({ userId: req.user.id, realPortfolioId, position })),
      { transaction }
    );

    await transaction.commit();
    res.status(201).json({ success: true, data: toApi(portfolio) });
  } catch (error) {
    if (!transaction.finished) await transaction.rollback();
    next(error);
  }
};

exports.deleteRealPortfolio = async (req, res, next) => {
  const transaction = await sequelize.transaction();
  try {
    const portfolio = await Portafoglio.findOne({
      where: { id: req.params.id, userId: req.user.id, tipo: 'reale' },
      transaction,
      lock: transaction.LOCK.UPDATE
    });
    if (!portfolio) {
      await transaction.rollback();
      return res.status(404).json({ success: false, error: 'Portafoglio reale non trovato' });
    }
    await portfolio.destroy({ transaction });
    await transaction.commit();
    res.status(200).json({ success: true });
  } catch (error) {
    if (!transaction.finished) await transaction.rollback();
    next(error);
  }
};


exports.createOperation = async (req, res, next) => {
  const transaction = await sequelize.transaction();
  try {
    const portfolio = await Portafoglio.findOne({
      where: { id: req.params.id, userId: req.user.id, tipo: 'reale', status: 'open' },
      transaction,
      lock: transaction.LOCK.UPDATE
    });
    if (!portfolio) {
      await transaction.rollback();
      return res.status(404).json({ success: false, error: 'Portafoglio reale non trovato' });
    }

    const operationType = String(req.body?.operationType ?? '');
    const etfId = String(req.body?.etfId ?? '');
    const operationDate = String(req.body?.operationDate ?? '');
    const quantity = Number(req.body?.quantity);
    const unitPrice = Number(req.body?.unitPrice);

    if (!['buy', 'sell'].includes(operationType)) {
      await transaction.rollback();
      return res.status(400).json({ success: false, error: 'Tipo operazione non valido' });
    }
    if (!etfId || !operationDate || !Number.isFinite(quantity) || quantity <= 0 || !Number.isFinite(unitPrice) || unitPrice <= 0) {
      await transaction.rollback();
      return res.status(400).json({ success: false, error: 'ETF, data, quantità e valore unitario sono obbligatori e devono essere validi' });
    }

    const etf = await ETF.findByPk(etfId, { transaction });
    if (!etf) {
      await transaction.rollback();
      return res.status(404).json({ success: false, error: 'ETF non trovato' });
    }

    let position = await RealPortfolioEtf.findOne({
      where: { realPortfolioId: portfolio.id, etfId },
      transaction,
      lock: transaction.LOCK.UPDATE
    });
    const currentQuantity = Number(position?.quantity ?? 0);
    const nextQuantity = operationType === 'buy' ? currentQuantity + quantity : currentQuantity - quantity;

    if (nextQuantity < 0) {
      await transaction.rollback();
      return res.status(400).json({ success: false, error: 'Quantità da vendere superiore alla posizione disponibile' });
    }

    const operation = await RealPortfolioOperation.create({
      userId: req.user.id, realPortfolioId: portfolio.id, operationType, etfId, operationDate, quantity, unitPrice
    }, { transaction });

    if (position) {
      if (nextQuantity === 0) await position.destroy({ transaction });
      else await position.update({ quantity: nextQuantity }, { transaction });
    } else {
      if (operationType !== 'buy') {
        await transaction.rollback();
        return res.status(400).json({ success: false, error: 'ETF non presente nel portafoglio' });
      }
      position = await RealPortfolioEtf.create({ realPortfolioId: portfolio.id, etfId, quantity: nextQuantity }, { transaction });
    }

    // Rebuild tax withholdings from the complete chronological trade history.
    // Historical inserts are therefore handled exactly like operations entered in date order.
    await RealPortfolioOperation.destroy({
      where: { userId: req.user.id, realPortfolioId: portfolio.id, operationType: 'tax' },
      transaction
    });

    const chronologicalOperations = await RealPortfolioOperation.findAll({
      where: {
        userId: req.user.id,
        realPortfolioId: portfolio.id,
        operationType: { [Op.in]: ['buy', 'sell'] }
      },
      attributes: ['id', 'operationType', 'etfId', 'quantity', 'unitPrice', 'operationDate', 'createdAt'],
      order: [['operationDate', 'ASC'], ['createdAt', 'ASC'], ['id', 'ASC']],
      transaction
    });

    const TAX_RATE = 0.26;
    const fiscalPositions = new Map();
    const taxRows = [];

    for (const historicalOperation of chronologicalOperations) {
      const historicalQuantity = Number(historicalOperation.quantity);
      const historicalUnitPrice = Number(historicalOperation.unitPrice);
      const historicalValue = historicalQuantity * historicalUnitPrice;
      const fiscal = fiscalPositions.get(String(historicalOperation.etfId)) || { quantity: 0, cost: 0 };

      if (historicalOperation.operationType === 'buy') {
        fiscal.quantity += historicalQuantity;
        fiscal.cost += historicalValue;
      } else {
        const averageCost = fiscal.quantity > 0 ? fiscal.cost / fiscal.quantity : 0;
        const realizedGain = (historicalUnitPrice - averageCost) * historicalQuantity;
        const withholding = realizedGain > 0 ? Math.round(realizedGain * TAX_RATE * 100) / 100 : 0;

        fiscal.quantity -= historicalQuantity;
        fiscal.cost -= averageCost * historicalQuantity;
        if (Math.abs(fiscal.quantity) < 1e-8) {
          fiscal.quantity = 0;
          fiscal.cost = 0;
        }

        if (withholding > 0) {
          taxRows.push({
            userId: req.user.id,
            realPortfolioId: portfolio.id,
            operationType: 'tax',
            etfId: null,
            operationDate: historicalOperation.operationDate,
            quantity: 1,
            unitPrice: withholding
          });
        }
      }

      fiscalPositions.set(String(historicalOperation.etfId), fiscal);
    }

    if (taxRows.length) await RealPortfolioOperation.bulkCreate(taxRows, { transaction });

    await portfolio.update({ dataModifica: new Date() }, { transaction });

    await transaction.commit();
    res.status(201).json({
      success: true,
      data: {
        id: operation.id, portfolioId: operation.realPortfolioId, operationType: operation.operationType,
        etf: { id: etf.id, isin: etf.isin, ticker: etf.ticker, name: etf.name, nickname: etf.nickname },
        operationDate: operation.operationDate, quantity: operation.quantity, unitPrice: operation.unitPrice,
        portfolioQuantity: nextQuantity
      }
    });
  } catch (error) {
    if (!transaction.finished) await transaction.rollback();
    next(error);
  }
};

const buildCurrentCostBasis = async (portfolioId) => {
  const operations = await RealPortfolioOperation.findAll({
    where: { realPortfolioId: portfolioId, operationType: { [Op.in]: ['buy', 'sell'] } },
    attributes: ['operationType', 'etfId', 'quantity', 'unitPrice', 'operationDate', 'createdAt', 'id'],
    order: [['operationDate', 'ASC'], ['createdAt', 'ASC'], ['id', 'ASC']],
    raw: true
  });
  const basis = new Map();
  for (const operation of operations) {
    const key = String(operation.etfId);
    const quantity = Number(operation.quantity);
    const value = quantity * Number(operation.unitPrice);
    const current = basis.get(key) || { quantity: 0, cost: 0 };
    if (operation.operationType === 'buy') {
      current.quantity += quantity;
      current.cost += value;
    } else {
      const averageCost = current.quantity > 0 ? current.cost / current.quantity : 0;
      current.quantity -= quantity;
      current.cost -= averageCost * quantity;
      if (Math.abs(current.quantity) < 1e-8) { current.quantity = 0; current.cost = 0; }
    }
    basis.set(key, current);
  }
  return basis;
};

exports.getHoldings = async (req, res, next) => {
  try {
    const portfolio = await Portafoglio.findOne({
      where: { id: req.params.id, userId: req.user.id, tipo: 'reale', status: 'open' }
    });
    if (!portfolio) return res.status(404).json({ success: false, error: 'Portafoglio reale non trovato' });

    const holdings = await RealPortfolioEtf.findAll({
      where: { realPortfolioId: portfolio.id },
      include: [{ model: ETF, as: 'etf', attributes: ['id', 'isin', 'ticker', 'name', 'nickname'] }],
      order: [['etfId', 'ASC']]
    });
    const basis = await buildCurrentCostBasis(portfolio.id);
    const isins = holdings.map(row => row.etf?.isin).filter(Boolean);
    const quotations = isins.length ? await EtfQuotation.findAll({
      where: { isin: { [Op.in]: isins }, quotation: { [Op.ne]: null } },
      attributes: ['isin', 'quotation', 'date'],
      order: [['isin', 'ASC'], ['date', 'DESC']],
      raw: true
    }) : [];
    const latestByIsin = new Map();
    for (const quote of quotations) if (!latestByIsin.has(quote.isin)) latestByIsin.set(quote.isin, quote);

    res.status(200).json({ success: true, data: holdings.map((row) => {
      const quantity = Number(row.quantity);
      const cost = basis.get(String(row.etf.id))?.cost ?? 0;
      const averageCost = quantity > 0 ? cost / quantity : 0;
      const quote = latestByIsin.get(row.etf.isin);
      const currentPrice = quote ? Number(quote.quotation) : null;
      const marketValue = currentPrice == null ? null : quantity * currentPrice;
      const gainLoss = marketValue == null ? null : marketValue - cost;
      return {
        id: row.etf.id, isin: row.etf.isin, ticker: row.etf.ticker, name: row.etf.name,
        nickname: row.etf.nickname, quantity, averageCost, investedCapital: cost,
        currentPrice, marketValue, gainLoss,
        gainLossPercent: cost > 0 && gainLoss != null ? gainLoss / cost * 100 : null,
        quotationDate: quote ? String(quote.date) : null
      };
    }) });
  } catch (error) { next(error); }
};

exports.getOperations = async (req, res, next) => {
  try {
    const portfolio = await Portafoglio.findOne({ where: { id: req.params.id, userId: req.user.id, tipo: 'reale' } });
    if (!portfolio) return res.status(404).json({ success: false, error: 'Portafoglio reale non trovato' });
    const operations = await RealPortfolioOperation.findAll({
      where: { userId: req.user.id, realPortfolioId: portfolio.id },
      include: [{ model: ETF, as: 'etf', attributes: ['id', 'isin', 'ticker', 'name', 'nickname'] }],
      order: [['operationDate', 'DESC'], ['createdAt', 'DESC']]
    });
    res.status(200).json({ success: true, data: operations.map((o) => ({
      id: o.id, operationType: o.operationType, operationDate: o.operationDate,
      quantity: o.quantity, unitPrice: o.unitPrice,
      total: o.operationType === 'tax' ? -Number(o.unitPrice) : Number(o.quantity) * Number(o.unitPrice),
      etf: o.etf
    })) });
  } catch (error) { next(error); }
};


exports.getLatestOperations = async (req, res, next) => {
  try {
    const portfolio = await Portafoglio.findOne({
      where: { id: req.params.id, userId: req.user.id, tipo: 'reale' }
    });
    if (!portfolio) return res.status(404).json({ success: false, error: 'Portafoglio reale non trovato' });

    const operations = await RealPortfolioOperation.findAll({
      where: { userId: req.user.id, realPortfolioId: portfolio.id },
      include: [{ model: ETF, as: 'etf', attributes: ['id', 'isin', 'ticker', 'name', 'nickname'] }],
      order: [['operationDate', 'DESC'], ['createdAt', 'DESC']],
      limit: 5
    });

    res.status(200).json({ success: true, data: operations.map((o) => ({
      id: o.id,
      operationType: o.operationType,
      operationDate: o.operationDate,
      quantity: o.quantity,
      unitPrice: o.unitPrice,
      total: o.operationType === 'tax' ? -Number(o.unitPrice) : Number(o.quantity) * Number(o.unitPrice),
      etf: o.etf
    })) });
  } catch (error) { next(error); }
};


const buildMarketValueSummary = async (portfolio) => {
  const positions = await RealPortfolioEtf.findAll({
    where: { realPortfolioId: portfolio.id },
    include: [{ model: ETF, as: 'etf', attributes: ['id', 'isin'] }]
  });
  if (!positions.length) {
    return { portfolioId: portfolio.id, marketValue: 0, investedCapital: 0, gainLoss: 0, gainLossPercent: 0, quotationDate: null };
  }

  const basis = await buildCurrentCostBasis(portfolio.id);
  const investedCapital = positions.reduce((sum, position) => sum + Number(basis.get(String(position.etf.id))?.cost ?? 0), 0);
  const isins = positions.map((row) => row.etf?.isin).filter(Boolean);
  const quotations = await EtfQuotation.findAll({
    where: { isin: { [Op.in]: isins }, quotation: { [Op.ne]: null } },
    attributes: ['isin', 'quotation', 'date'],
    order: [['isin', 'ASC'], ['date', 'DESC']],
    raw: true
  });
  const latestByIsin = new Map();
  for (const quote of quotations) if (!latestByIsin.has(quote.isin)) latestByIsin.set(quote.isin, quote);

  let marketValue = 0;
  const usedDates = [];
  for (const position of positions) {
    const quote = latestByIsin.get(position.etf?.isin);
    if (!quote) continue;
    marketValue += Number(position.quantity) * Number(quote.quotation);
    usedDates.push(String(quote.date));
  }
  const gainLoss = marketValue - investedCapital;
  return {
    portfolioId: portfolio.id, marketValue, investedCapital, gainLoss,
    gainLossPercent: investedCapital > 0 ? gainLoss / investedCapital * 100 : 0,
    quotationDate: usedDates.length === positions.length ? usedDates.sort()[0] : null
  };
};

exports.getMarketValueSummaries = async (req, res, next) => {
  try {
    const portfolios = await Portafoglio.findAll({
      where: { status: 'open', tipo: 'reale', userId: req.user.id },
      order: [['dataCreazione', 'DESC']]
    });
    const data = [];
    for (const portfolio of portfolios) data.push(await buildMarketValueSummary(portfolio));
    res.status(200).json({ success: true, data });
  } catch (error) { next(error); }
};

exports.getMarketValueSummary = async (req, res, next) => {
  try {
    const portfolio = await Portafoglio.findOne({ where: { id: req.params.id, status: 'open', tipo: 'reale', userId: req.user.id } });
    if (!portfolio) return res.status(404).json({ success: false, error: 'Portafoglio reale non trovato' });
    res.status(200).json({ success: true, data: await buildMarketValueSummary(portfolio) });
  } catch (error) { next(error); }
};


exports.updateRealPortfolioOrder = async (req, res, next) => {
  const transaction = await sequelize.transaction();
  try {
    const ids = Array.isArray(req.body?.portfolioIds) ? req.body.portfolioIds.map(String) : [];
    if (!ids.length || ids.length > 5 || new Set(ids).size !== ids.length) {
      await transaction.rollback();
      return res.status(400).json({ success: false, error: 'Ordine portafogli non valido' });
    }
    const portfolios = await Portafoglio.findAll({
      where: { userId: req.user.id, tipo: 'reale', status: 'open' },
      attributes: ['id'], transaction
    });
    const ownedIds = portfolios.map(p=>String(p.id));
    if (ids.length !== ownedIds.length || ids.some(id=>!ownedIds.includes(id))) {
      await transaction.rollback();
      return res.status(400).json({ success: false, error: 'L’ordine deve contenere tutti i portafogli reali aperti' });
    }
    await RealPortfolioOrder.destroy({ where: { userId: req.user.id }, transaction });
    await RealPortfolioOrder.bulkCreate(ids.map((realPortfolioId, position)=>({ userId:req.user.id, realPortfolioId, position })), { transaction });
    await transaction.commit();
    res.status(200).json({ success: true });
  } catch(error) {
    if (!transaction.finished) await transaction.rollback();
    next(error);
  }
};
